#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=8g,walltime=2:00:00
#PBS -N app-synthstrip
#PBS -V


#set -e

t1=$(jq -r .t1 config.json)
t2=$(jq -r .t2 config.json)
no_csf=$( jq -r .no_csf config.json )
use_gpu=$( jq -r .use_gpu config.json )

# Custom singularity runner
singularity_run() {
    singularity exec -e docker://"$1" "${@:2}"
}

if [ "${t1}" != "null" ]; then
    input=$t1
    outputdir=t1_brain
    output=t1.nii.gz
elif [ "${t2}" != "null" ]; then

    input=$t2
    outputdir=t2_brain
    output=t2.nii.gz   
else
    
    echo "Datatype not supported" >&2
    exit -1
fi

mkdir ${outputdir}
mkdir mask

no_csf_opt=''
[ "${no_csf}"  == "true" ] && { no_csf_opt=" --no-csf "; }

if [ "${use_gpu}" == "true" ]; then

    docker=freesurfer/synthstrip:1.7-gpu
else

    docker=freesurfer/synthstrip:1.7
fi

singularity_run ${docker} mri_synthstrip  -i ${input} -o ./${outputdir}/${output} -m ./mask/mask.nii.gz ${no_csf_opt}

