#!/bin/bash
#PBS -l nodes=1:ppn=1,vmem=8g,walltime=2:00:00
#PBS -N app-synthstrip
#PBS -V


#set -e

t1=$(jq -r .t1 config.json)
no_csf=$( j1 -r .no_csf condifg.json )
use_gpu=$( j1 -r .use_gpu condifg.json )

# Custom singularity runner
singularity_run() {
    singularity exec -e docker://"$1" "${@:2}"
}

mkdir t1_brain
mkdir mask

no_csf_opt=''
[ "${no_csf}"  == "true" ] && { no_csf_opt=" --no-csf "; }

if [ "${gpu}" == "true" ]; then

    freesurfer/synthstrip:1.7-gpu
else

    freesurfer/synthstrip:1.7
fi

singularity_run ${docker} mri_synthstrip  -i ${t1} -o ./t1_brain/t1.nii.gz -m ./mask/mask.nii.gz ${no_csf_opt}

